language: node_js
node_js:
  - "node"
cache:
  directories:
    - ~/.npm
script:
- npm test
notifications:
  email: false
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: out
  on:
    branch: master